apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: microenv-operator
    app.kubernetes.io/part-of: microenv-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
imagePullSecrets:
  - name: obsjfrogregistry
---
apiVersion: v1
kind: Secret
metadata:
  name: obsjfrogregistry
  namespace: system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ewogICJhdXRocyI6IHsKICAgICJkbXAtdmlydHVhbC1wdWJsaWMtcmVwby5wdWItcmVwby5wcm9kLnVzLXdlc3QtMi5hd3MuZmljby5jb20iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJkbXBfc2VydmljZSIsCiAgICAgICJwYXNzd29yZCI6ICI1WVBobE9lclN0bE9KTCIsCiAgICAgICJlbWFpbCI6ICJkbXBhZG1pbkBmaWNvLmNvbSIsCiAgICAgICJhdXRoIjogIlpHMXdYM05sY25acFkyVTZOVmxRYUd4UFpYSlRkR3hQU2t3PSIKICAgIH0sCiAgICAiZG1wLXZpcnR1YWwtcHVibGljLXJlcG8ucmVwby5wcm9kLnVzLXdlc3QtMi5hd3MuZmljby5jb20iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJkbXBfc2VydmljZSIsCiAgICAgICJwYXNzd29yZCI6ICI1WVBobE9lclN0bE9KTCIsCiAgICAgICJlbWFpbCI6ICJkbXBhZG1pbkBmaWNvLmNvbSIsCiAgICAgICJhdXRoIjogIlpHMXdYM05sY25acFkyVTZOVmxRYUd4UFpYSlRkR3hQU2t3PSIKICAgIH0sCiAgICAiZG1wLWRvY2tlci1kZXZlbG9wbWVudC5yZXBvLnByb2QudXMtd2VzdC0yLmF3cy5maWNvLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogImRtcF9zZXJ2aWNlIiwKICAgICAgInBhc3N3b3JkIjogIjVZUGhsT2VyU3RsT0pMIiwKICAgICAgImVtYWlsIjogImRtcGFkbWluQGZpY28uY29tIiwKICAgICAgImF1dGgiOiAiWkcxd1gzTmxjblpwWTJVNk5WbFFhR3hQWlhKVGRHeFBTa3c9IgogICAgfSwKICAgICJvYnMtZG9ja2VyLWRldmVsb3BtZW50LnB1Yi1yZXBvLnByb2QudXMtd2VzdC0yLmF3cy5maWNvLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogImRtcF9zZXJ2aWNlIiwKICAgICAgInBhc3N3b3JkIjogIjVZUGhsT2VyU3RsT0pMIiwKICAgICAgImVtYWlsIjogImRtcGFkbWluQGZpY28uY29tIiwKICAgICAgImF1dGgiOiAiWkcxd1gzTmxjblpwWTJVNk5WbFFhR3hQWlhKVGRHeFBTa3c9IgogICAgfSwKICAgICJvYnMtZG9ja2VyLWRldmVsb3BtZW50LnJlcG8ucHJvZC51cy13ZXN0LTIuYXdzLmZpY28uY29tIjogewogICAgICAidXNlcm5hbWUiOiAiZG1wX3NlcnZpY2UiLAogICAgICAicGFzc3dvcmQiOiAiNVlQaGxPZXJTdGxPSkwiLAogICAgICAiZW1haWwiOiAiZG1wYWRtaW5AZmljby5jb20iLAogICAgICAiYXV0aCI6ICJaRzF3WDNObGNuWnBZMlU2TlZsUWFHeFBaWEpUZEd4UFNrdz0iCiAgICB9CiAgfQp9

